telescope:
  build: telescope-on-docker
  ports:
    - "3000:3000"
  env_file: .env
  links:
    - datadog
    - mongodb

mongodb:
  image: mongo:3.0.1
  volumes:
    - data:/data/db
  expose:
    - "27017"

datadog:
  image: datadog/docker-dd-agent:5.2.1
  env_file: .env
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /proc/mounts:/host/proc/mounts:ro
    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
